#!/bin/bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)  
repoName=${IMAGE_NAME:0:tagStart-1}

# Tag and push image for each additional tag
for tag in {latest,$(date +%Y%m%d%H%M%S)}; do  
    docker tag $IMAGE_NAME ${repoName}:unbound-${tag}
    docker push ${repoName}:unbound-${tag}
done
